
    #define SETA_OFF           0    /* Janela sem bot†o de seta.                */
    #define SETA_CIM           90   /* Janela c/ seta p/ cima.                  */
    #define SETA_ESQ           180  /* Janela c/ seta p/ esquerda.              */
    #define SETA_BAI           270  /* Janela c/ seta p/ baixo.                 */
    #define SETA_DIR           360  /* Janela c/ seta p/ direita.               */
    #define CLIP_ON            1    /* Ativa o Clipping na Janela de exibi‡†o.  */
    #define CLIP_OFF           0    /* Desativa o Clipping na Janela de vis†o.  */
    #define APAGA_JANELA       1    /* Apaga a janela de exibi‡†o.              */
    #define NAO_APAGA_JANELA   0    /* N†o apaga Janela de exibi‡†o.            */
